pipeline:
  build:
    image: golang:1.8
    environment:
      - GOPATH=/drone
      - GOOS=linux 
      - GOARCH=amd64 
      - CGO_ENABLED=0 
    commands:
      - go build -o drone-sonarqube-node

  publish:
    image: plugins/docker
    repo: committed/drone-sonarqube-node
    secrets: [ docker_username, docker_password ]
    tag: [ '1.0.0', latest ]
    when:
      branch: master
      event: push
